import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const fontSerif = Lora({subsets:['latin'],variable:'--font-serif'});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={fontSerif.variable}>
      <body
        className="antialiased font-serif"
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}